---
abstract: 'Loading Perl modules from their development directories'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-SearchINC
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Find: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.38
