---
abstract: 'Loading Perl modules from their development directories'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Carp: 0
  English: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101440, CPAN::Meta::Converter version 2.101410'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-SearchINC
provides:
  Devel::SearchINC:
    file: lib/Devel/SearchINC.pm
    version: 2.101440
requires:
  Data::Dumper: 0
  File::Find: 0
  perl: 5.008
resources:
  homepage: http://search.cpan.org/dist/Devel-SearchINC/
  repository: http://github.com/hanekomu/Devel-SearchINC
version: 2.101440
