---
abstract: 'Loading Perl modules from their development directories'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-SearchINC
provides:
  Devel::SearchINC:
    file: lib/Devel/SearchINC.pm
    version: 1.100850
requires:
  Carp: 0
  Data::Dumper: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Devel-SearchINC
  homepage: http://search.cpan.org/dist/Devel-SearchINC/
  repository: http://github.com/hanekomu/Devel-SearchINC
version: 1.100850
